message:
  no_permission: "&cYou do not have permission to use this command"
  unknown_channel: "&cThe specified channel does not exist"
  not_player: "&cYou must be a player to use this command."
channel:
  staff:
    format: "&9[STAFF] {player} {message}"
    read: "sc.staff.read"
    write: "sc.staff.write"
  admin:
    format: "&c[ADMIN] {player} {message}"
    read: "sc.admin.read"
    write: "sc.admin.write"