# All customisable error messages so that you can keep it consistent across your plugins.
message:
  no_permission: "&cYou do not have permission to use this command"
  not_player: "&cYou must be a player to use this command."

# When a player logs out, should they keep the last channel they were chatting in, or reconnect to that same channel.
# Channels are NOT persistent across reboots. Yet.
default_channel_on_relog: true

# Here you can define as many channels as you'd like, each with their own permission and prefix.
## Each channel should have a unique name (why wouldn't you?)
## The message template can be customised with displayname, and message with {DISPLAYNAME}, and {MESSAGE} respectively.
channel:
  - staff:
      message: "&e[STAFF] {DISPLAYNAME}&f: {MESSAGE}"
      permission: "staffchat.staff"
  - admin:
      message: "&c[ADMIN] {DISPLAYNAME}&f: {MESSAGE}"
      permission: "staffchat.admin"
