name: StaffChat
version: ${project.version}
main: github.chriscn.StaffChat
api-version: 1.13
authors: [Thorin]
description: A plugin that allows your Staff Members to communicate in private.
commands:
  staffchat:
    usage: /staffchat <msg>
  channel:
    usage: /channel <all/staff/admin>
    aliases: [c]
  listchannel:
    usage: /listchannel