name: StaffChat
version: ${project.version}
main: github.chriscn.StaffChat
api-version: 1.13
authors: [Thorin]
description: A plugin that allows your Staff Members to communicate in private.
commands:
  channel:
    usage: /channel <channels>
    alias: [c]
  test:
    usage: /test
  debug:
    usage: /debug